### ISSUE TITLE
unable to load tdm

### ISSUE THREAD

**Issue by Aquapisces** [domna/tdm_loader#12] opened 2018-02-26 03:46 UTC
I cod as you told:
**data_file = tdm_loader.OpenFile('filename.tdm' [, encoding='utf-8'])**
and come across an "invalid syntax". 
After I tried removing the bracket, there's no "invalid syntax" any more, but a Unicode Encode Error:
**''ascii' codec can't encode character u'\xb0' in position 5305: ordinal not in range(128)**
Why?

**Comment by domna** [comment] 2018-02-26 08:01
First of all: the square brackets used in this example denote that the encoding is optional. Therefore, if you simply copy this example you will run into an invalid syntax error.
The correct example would be
**data_file = tdm_loader.OpenFile('filename.tdm' , encoding='utf-8')**
if you want to use utf-8 encoding (which you seem to want, regarding your second error) and read the file filename.tdm.

So I suggest that you try the call with utf-8 encoding without the square brackets and see if it works then.

**Comment by Aquapisces** [comment] 2018-02-26 08:59
Thanks!
However, I did remove the square brackets, used utf-8 encoding,  and then get the second error:
''ascii' codec can't encode character u'\xb0' in position 5305: ordinal not in range(128)
That's my real confusion

**Comment by domna** [comment] 2018-02-26 09:56
Could you provide the filename and actual file you are working with, so I can reproduce the error?
Apperently the problem is a degree sign (°) which has the unicode code\xb0, do you use this symbol anywhere in your data?

**Comment by Aquapisces** [comment] 2018-02-27 01:11
https://pan.baidu.com/s/1ggZ9z2N
I‘m sorry dropbox and onedrive are blocked in my country.
Please click on the download icon in this Chinese web to download the tdm file.
The tdm file is a record of some test data, and the degree sign(°) is the unit of temperature data.

**Comment by domna** [comment] 2018-02-27 11:05
Unfortunately I need both files, the tdm and the tdx file. Because in the latter the actual binary data is saved. But I think I already found origin of the problem, I will correct and test it within the next days and upstream the corrected version to pypi.

**Comment by domna** [comment] 2018-02-27 22:59
Should be fixed in version 1.1.11 which is now available over pypi (and therefore by installation over pip)

**Closed as completed by domna** 2018-02-27 22:59 UTC

**Comment by Aquapisces** [comment] 2018-02-28 02:45
https://pan.baidu.com/s/1cZ32zW
Thank you so much for your all night hard working!
But version 1.1.11 seems to have another problem:
**TypeError: expected a readable buffer object**
I have uploaded the tdx file along with tdm. Please click the link ahead to achieve them.
Danke!

**Comment by domna** [comment] 2018-02-28 20:00
I cannot reproduce the error with your file. If I execute the following snippet with your tdm/tdx file I get no error:
```
import tdm_loader as tdm
  
data = tdm.OpenFile("2017_11_15_W352_352_ZP_test_001_2017_11_15_W352_350_ZP_test.tdm")
data.channel_dict(0)
```

Please provide more information on what OS and python version you are using. Additionally it would be useful if you could paste the full error trace here.

**Comment by Aquapisces** [comment] 2018-03-01 01:20
System information: Windows 10, 64bit
Python version: 2.7
I wonder why you don't type the path before the file name of tmd in tdm.openfile().
This is what I ran in ipython:

In [1]: import tdm_loader as tdm

In [2]: datafile=tdm.OpenFile("D:/Python/BD/tdm/2017_11_15_W352_352_ZP_test_001_2017_11_15_W352_350_ZP_test.tdm", encod
   ...: ing='utf-8')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-71ef92f9b8d1> in <module>()
----> 1 datafile=tdm.OpenFile("D:/Python/BD/tdm/2017_11_15_W352_352_ZP_test_001_2017_11_15_W352_350_ZP_test.tdm", encoding='utf-8')

c:\python27\lib\site-packages\tdm_loader-1.1.11-py2.7.egg\tdm_loader\tdm_loader.pyc in __init__(self, tdm_path, tdx_path, encoding)
     84         else:
     85             self._tdx_path = tdx_path
---> 86         self._open_tdx(self._tdx_path)
     87         self.channel_names = [chan.name for chan in self.tdm.channels]
     88

c:\python27\lib\site-packages\tdm_loader-1.1.11-py2.7.egg\tdm_loader\tdm_loader.pyc in _open_tdx(self, tdx_path)
    103             # data is in column first order
    104             # use the hacked solution for the memmap
--> 105             self._tdx_memmap = MemmapColumnFirst(self._tdx_fobj, self.tdm)
    106             self._memmap_type = 'Slow'
    107         elif self.tdm.exporter_type.find('LabVIEW') >= 0 or \

c:\python27\lib\site-packages\tdm_loader-1.1.11-py2.7.egg\tdm_loader\tdm_loader.pyc in __init__(self, fobj, tdm_file)
    572         self._num_channels = tdm_file.num_channels
    573         self._empty_row = np.recarray((1, ), tdm_file.dtype)
--> 574         self._empty_row[0] = 0 # initialize all items to zero
    575         channels = tdm_file.channels
    576         for i in range(len(channels)):

TypeError: expected a readable buffer object

**Comment by domna** [comment] 2018-03-01 07:42
This should work, for me it is working as well on my windows 10 machine.
In my snippet I'm not using any path because the tdm and tdx files lie in the same directory as my python file, therefore I can use the relative path to the script.

The problem which you now have is due to an older version of numpy. You do have a numpy version below 1.14, right? If so could you please update your numpy version to the newest version? This is normally done by the shell call
`pip install --upgrade numpy.`

I will upgrade the dependency requirement in the setup file as well, so there will be no problems in the future.

**Comment by Aquapisces** [comment] 2018-03-02 11:25
You're right, it runs well after I updated numpy.
It's very kind of you, a lot of thanks!
